[package]
name = "machinalearnen"
version = "0.1.0"
edition = "2021"

[dependencies]
egui-macroquad = "0.15.0"
image = "0.25.2"
macroquad = "0.3.26"
rand = "0.8.5"
rfd = "0.14.1"
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0"
